name: nutrition-tracker
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python==3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - pytorch
  - torchvision
  - pytorch
  - pytorch-cuda=11.8
  - bitsandbytes
  - sentencepiece
  - transformers
  - protobuf
  - ultralytics
  - scikit-learn
  - tqdm
  - wandb
  - ipykernel
  - pip:
    - accelerate
    - flash-attn